Log:
  Level: warning # Log level: none, error, warning, info, debug
  AccessPath: # /etc/XrayR/access.Log
  ErrorPath: # /etc/XrayR/error.log

DnsConfigPath: # /etc/XrayR/dns.json
RouteConfigPath: # /etc/XrayR/route.json
InboundConfigPath: # /etc/XrayR/custom_inbound.json
OutboundConfigPath: # /etc/XrayR/custom_outbound.json

ConnectionConfig:
  Handshake: 4 # Handshake time limit, Second
  ConnIdle: 30 # Connection idle time limit, Second
  UplinkOnly: 2 # Time limit when the connection downstream is closed, Second
  DownlinkOnly: 4 # Time limit when the connection is closed after the uplink is closed, Second
  BufferSize: 64 # The internal cache size of each connection, kB

Nodes:
  # 第一个节点配置
  - PanelType: "NewV2board"
    ApiConfig:
      ApiHost: "https://go.yueyun.de"
      ApiKey: "Lsj17721029596020705"
      NodeID: 85
      NodeType: V2ray
      Timeout: 30
      EnableVless: false
      VlessFlow: "xtls-rprx-vision"
      SpeedLimit: 0
      DeviceLimit: 0
      DisableCustomConfig: false
    ControllerConfig:
      ListenIP: 0.0.0.0
      SendIP: 0.0.0.0
      UpdatePeriodic: 60
      EnableDNS: false
      DNSType: AsIs
      EnableProxyProtocol: false
      AutoSpeedLimitConfig:
        Limit: 0
        WarnTimes: 0
        LimitSpeed: 0
        LimitDuration: 0
      GlobalDeviceLimitConfig:
        Enable: false
        RedisAddr: "127.0.0.1:6379"
        RedisPassword: "YOUR PASSWORD"
        RedisDB: 0
        Timeout: 5
        Expiry: 60
      EnableFallback: false
      FallBackConfigs:
        - SNI: ""
          Alpn: ""
          Path: ""
          Dest: 80
          ProxyProtocolVer: 0
      DisableLocalREALITYConfig: false
      EnableREALITY: false
      REALITYConfigs:
        Show: true
        Dest: "www.smzdm.com:443"
        ProxyProtocolVer: 0
        ServerNames:
          - "www.smzdm.com"
        PrivateKey: "YOUR_PRIVATE_KEY"
        MinClientVer: ""
        MaxClientVer: ""
        MaxTimeDiff: 0
        ShortIds:
          - ""
          - "0123456789abcdef"
      CertConfig:
        CertMode: dns
        CertDomain: "dmitv61.616626.xyz"
        CertFile: "/etc/XrayR/cert/node1.test.com.cert"
        KeyFile: "/etc/XrayR/cert/node1.test.com.key"
        Provider: "cloudflare"
        Email: "test@me.com"
        DNSEnv:
          CLOUDFLARE_EMAIL: "phosic1986@gmail.com"
          CLOUDFLARE_API_KEY: "5ef1bf78bdb9537959e33429c7531a9ecb58f"

  # 第二个节点配置
  - PanelType: "NewV2board"
    ApiConfig:
      ApiHost: "https://go.yueyun.de"
      ApiKey: "Lsj17721029596020705"
      NodeID: 73
      NodeType: V2ray
      Timeout: 30
      EnableVless: false
      VlessFlow: "xtls-rprx-vision"
      SpeedLimit: 0
      DeviceLimit: 0
      DisableCustomConfig: false
    ControllerConfig:
      ListenIP: 0.0.0.0
      SendIP: 0.0.0.0
      UpdatePeriodic: 60
      EnableDNS: false
      DNSType: AsIs
      EnableProxyProtocol: false
      AutoSpeedLimitConfig:
        Limit: 0
        WarnTimes: 0
        LimitSpeed: 0
        LimitDuration: 0
      GlobalDeviceLimitConfig:
        Enable: false
        RedisAddr: "127.0.0.1:6379"
        RedisPassword: "YOUR PASSWORD"
        RedisDB: 0
        Timeout: 5
        Expiry: 60
      EnableFallback: false
      FallBackConfigs:
        - SNI: ""
          Alpn: ""
          Path: ""
          Dest: 80
          ProxyProtocolVer: 0
      DisableLocalREALITYConfig: false
      EnableREALITY: false
      REALITYConfigs:
        Show: true
        Dest: "www.smzdm.com:443"
        ProxyProtocolVer: 0
        ServerNames:
          - "www.smzdm.com"
        PrivateKey: "YOUR_PRIVATE_KEY"
        MinClientVer: ""
        MaxClientVer: ""
        MaxTimeDiff: 0
        ShortIds:
          - ""
          - "0123456789abcdef"
      CertConfig:
        CertMode: dns
        CertDomain: "dmitv4.656888.xyz"
        CertFile: "/etc/XrayR/cert/node1.test.com.cert"
        KeyFile: "/etc/XrayR/cert/node1.test.com.key"
        Provider: "cloudflare"
        Email: "test@me.com"
        DNSEnv:
          CLOUDFLARE_EMAIL: "phosic1986@gmail.com"
          CLOUDFLARE_API_KEY: "5ef1bf78bdb9537959e33429c7531a9ecb58f"
